# -*- coding: utf-8 -*-
"""meetnotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6N83zIN6-cmdSl6rR1QQmY6qJy_ohxA
"""

import torch

print("=" * 70)
print("FRESH COLAB RUNTIME")
print("=" * 70)

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:",
          round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
          "GB")

print("=" * 70)

!pip install -q \
    "torch>=2.7.0" \
    "transformers>=4.52.0,<5" \
    "librosa" \
    "huggingface_hub"

import torch
import transformers
import huggingface_hub

print("=" * 70)
print("PARROTLET ENVIRONMENT")
print("=" * 70)

print("PyTorch         :", torch.__version__)
print("Transformers    :", transformers.__version__)
print("HuggingFace Hub :", huggingface_hub.__version__)
print("CUDA available  :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU             :", torch.cuda.get_device_name(0))

print("=" * 70)

from transformers import AutoModel

print("AutoModel import: SUCCESS")

import torch

print("GPU:", torch.cuda.get_device_name(0))
print("VRAM:",
      round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
      "GB")

!free -h

!df -h

!nvidia-smi

import accelerate

print("Accelerate:", accelerate.__version__)

import transformers
import huggingface_hub

print("Transformers:", transformers.__version__)
print("HF Hub:", huggingface_hub.__version__)

!pip install -q --force-reinstall \
    "transformers>=4.52.0,<5" \
    "huggingface_hub>=0.34.0,<1.0"

import torch, transformers, huggingface_hub, accelerate

print("PyTorch :", torch.__version__)
print("Transformers :", transformers.__version__)
print("HuggingFace Hub :", huggingface_hub.__version__)
print("Accelerate :", accelerate.__version__)
print("CUDA available :", torch.cuda.is_available())

from google.colab import userdata
from huggingface_hub import login

hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)

!pip uninstall -y transformers
!pip install git+https://github.com/huggingface/transformers.git

import transformers
print(transformers.__version__)

from transformers import AutoModel

model = AutoModel.from_pretrained("ekacare/parrotlet-a-2.5-pro", trust_remote_code=True, device_map="auto")

print("=" * 70)
print("PARROTLET-A LOADED")
print("=" * 70)

print("Model class:", type(model))
print("Model device:", next(model.parameters()).device)
print("Model dtype:", next(model.parameters()).dtype)

from google.colab import files

uploaded = files.upload()

import librosa
import time

audio_path = "Recording 4.wav"

audio_16k, sample_rate_16k = librosa.load(
    audio_path,
    sr=16000
)

print("=" * 70)
print("ENGLISH AUDIO PREPARATION")
print("=" * 70)

print("Original file:", audio_path)
print("Resampled rate:", sample_rate_16k)
print("Duration:", round(len(audio_16k) / sample_rate_16k, 2), "seconds")

import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

from transformers import AutoModel

MODEL_ID = "ekacare/parrotlet-a-2.5-pro"

print("Loading Parrotlet-A...")

model = AutoModel.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    device_map="auto"
)

print("=" * 70)
print("PARROTLET-A LOADED")
print("=" * 70)
print("Model class:", type(model))
print("Device:", next(model.parameters()).device)
print("Dtype:", next(model.parameters()).dtype)

import os

print(os.path.exists("Recording 4.wav"))

import librosa

audio_16k, sample_rate_16k = librosa.load(
    "Recording 4.wav",
    sr=16000
)

print("Sample rate:", sample_rate_16k)
print("Duration:", round(len(audio_16k) / sample_rate_16k, 2), "seconds")

def fixed_preprocess_audio(audio_data, orig_sr):
    return audio_data

model.preprocess_audio = fixed_preprocess_audio

print("Preprocess workaround applied.")

import torch
import time

print("=" * 70)
print("PARROTLET-A — DTYPE FIX")
print("=" * 70)

# Convert NumPy float32 audio to BF16
audio_bf16 = torch.from_numpy(audio_16k).to(
    device="cuda",
    dtype=torch.bfloat16
)

print("Audio tensor dtype:", audio_bf16.dtype)
print("Audio tensor device:", audio_bf16.device)

import torch

# Keep audio as NumPy float32.
# We will convert the extracted Whisper features to BF16 instead.

def fixed_preprocess_audio(audio_data, orig_sr):
    return audio_data

model.preprocess_audio = fixed_preprocess_audio

print("Preprocess function patched.")
print("Audio input:", type(audio_16k), audio_16k.dtype)
print("Sample rate:", 16000)

audio_features = model.processor.feature_extractor(
    [audio_16k],
    sampling_rate=model.sampling_rate,
    return_tensors="pt"
).input_features

print("Feature dtype before:", audio_features.dtype)

encoder_dtype = model.encoder.conv1.weight.dtype

print("Encoder dtype:", encoder_dtype)

audio_features = audio_features.to(
    device=next(model.encoder.parameters()).device,
    dtype=encoder_dtype
)

print("Feature dtype after :", audio_features.dtype)
print("Feature device      :", audio_features.device)

import torch
import time

def parrotlet_transcribe_fixed(
    model,
    audio,
    orig_sr,
    max_new_tokens=128,
    repetition_penalty=1.2,
):
    device = next(model.parameters()).device

    print("=" * 70)
    print("PARROTLET-A FIXED TRANSCRIPTION PIPELINE")
    print("=" * 70)

    # --------------------------------------------------------
    # 1. Original Parrotlet prompt
    # --------------------------------------------------------

    prompt = model.get_prompt()

    input_ids = torch.tensor(
        model.tokenizer(
            prompt,
            add_special_tokens=False
        )["input_ids"],
        dtype=torch.long,
        device=device
    ).unsqueeze(0)

    input_attention_mask = torch.ones_like(input_ids)

    # --------------------------------------------------------
    # 2. Locate audio token
    # --------------------------------------------------------

    audio_token = model.tokenizer.convert_tokens_to_ids(
        model.audio_token
    )

    audio_pos = input_ids[0].tolist().index(audio_token)

    print("Audio token position:", audio_pos)

    # --------------------------------------------------------
    # 3. Audio is ALREADY 16 kHz
    # --------------------------------------------------------

    processed_audio = audio

    print("Audio sample rate:", orig_sr)
    print("Audio samples:", len(processed_audio))

    # --------------------------------------------------------
    # 4. Feature extraction
    # --------------------------------------------------------

    audio_features = model.processor.feature_extractor(
        [processed_audio],
        sampling_rate=model.sampling_rate,
        return_tensors="pt"
    ).input_features

    # IMPORTANT:
    # Feature extractor produces float32.
    # Whisper encoder is BF16.
    # Convert HERE.
    encoder_dtype = model.encoder.conv1.weight.dtype

    audio_features = audio_features.to(
        device=device,
        dtype=encoder_dtype
    )

    print("Audio feature dtype:", audio_features.dtype)
    print("Encoder dtype:", encoder_dtype)

    # --------------------------------------------------------
    # 5. Whisper encoder
    # --------------------------------------------------------

    with torch.no_grad():
        audio_embeddings = model.encoder(
            audio_features
        ).last_hidden_state

    print("Encoder output:", audio_embeddings.shape)
    print("Encoder output dtype:", audio_embeddings.dtype)

    # --------------------------------------------------------
    # 6. Projector
    # --------------------------------------------------------

    projector_dtype = next(
        model.projector.parameters()
    ).dtype

    print("Projector dtype:", projector_dtype)

    audio_embeddings_projector = audio_embeddings.to(
        projector_dtype
    )

    with torch.no_grad():
        projected_audio_embeddings = model.projector(
            audio_embeddings_projector
        )

    print(
        "Projected audio:",
        projected_audio_embeddings.shape
    )
    print(
        "Projected audio dtype:",
        projected_audio_embeddings.dtype
    )

    # --------------------------------------------------------
    # 7. Decoder text embeddings
    # --------------------------------------------------------

    input_embeddings = model.decoder.get_input_embeddings()(
        input_ids
    )

    decoder_dtype = input_embeddings.dtype

    print("Decoder dtype:", decoder_dtype)

    projected_audio_embeddings = (
        projected_audio_embeddings.to(decoder_dtype)
    )

    # --------------------------------------------------------
    # 8. Combine text + audio embeddings
    # --------------------------------------------------------

    batch_size, input_seq_len, embed_dim = (
        input_embeddings.shape
    )

    audio_seq_len = projected_audio_embeddings.shape[1]

    combined_len = (
        input_seq_len +
        audio_seq_len -
        1
    )

    combined_embeddings = torch.zeros(
        batch_size,
        combined_len,
        embed_dim,
        device=device,
        dtype=decoder_dtype
    )

    combined_attention_mask = torch.zeros(
        batch_size,
        combined_len,
        device=device,
        dtype=torch.long
    )

    # Text before audio
    combined_embeddings[
        :, :audio_pos
    ] = input_embeddings[
        :, :audio_pos
    ]

    combined_attention_mask[
        :, :audio_pos
    ] = 1

    # Audio
    combined_embeddings[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = projected_audio_embeddings

    combined_attention_mask[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = 1

    # Text after audio
    suffix_start = audio_pos + 1
    suffix_len = input_seq_len - suffix_start
    out_start = audio_pos + audio_seq_len

    if suffix_len > 0:
        combined_embeddings[
            :,
            out_start:out_start + suffix_len
        ] = input_embeddings[
            :,
            suffix_start:
        ]

        combined_attention_mask[
            :,
            out_start:out_start + suffix_len
        ] = 1

    print()
    print("Combined embeddings:", combined_embeddings.shape)
    print("Combined dtype:", combined_embeddings.dtype)

    # --------------------------------------------------------
    # 9. IMPORTANT:
    # Use decoder.generate with the combined embeddings.
    #
    # We do NOT pass input_ids because Transformers 4.57
    # may reject inputs_embeds for this Gemma class.
    #
    # Instead, provide the embeddings through a custom
    # generation call using the decoder's forward method.
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("DECODER")
    print("=" * 70)

    # First verify that Gemma itself accepts inputs_embeds.
    with torch.no_grad():
        test_output = model.decoder(
            inputs_embeds=combined_embeddings,
            attention_mask=combined_attention_mask,
            use_cache=False
        )

    print("Decoder forward: SUCCESS")
    print("Logits shape:", test_output.logits.shape)

    return test_output


print("=" * 70)
print("STARTING PARROTLET-A ENGLISH TEST")
print("=" * 70)

start = time.time()

output = parrotlet_transcribe_fixed(
    model=model,
    audio=audio_16k,
    orig_sr=16000,
    max_new_tokens=128
)

elapsed = time.time() - start

print()
print("=" * 70)
print("PIPELINE TEST COMPLETE")
print("=" * 70)
print("Inference/forward time:", round(elapsed, 2), "seconds")

import torch
import time

def parrotlet_transcribe_fixed(
    model,
    audio,
    orig_sr,
    max_new_tokens=128,
    repetition_penalty=1.2,
):
    device = next(model.parameters()).device

    print("=" * 70)
    print("PARROTLET-A FIXED TRANSCRIPTION PIPELINE")
    print("=" * 70)

    # --------------------------------------------------------
    # 1. Parrotlet original prompt
    # --------------------------------------------------------

    prompt = model.get_prompt()

    input_ids = torch.tensor(
        model.tokenizer(
            prompt,
            add_special_tokens=False
        )["input_ids"],
        dtype=torch.long,
        device=device
    ).unsqueeze(0)

    input_attention_mask = torch.ones_like(input_ids)

    # --------------------------------------------------------
    # 2. Find audio token
    # --------------------------------------------------------

    audio_token = model.tokenizer.convert_tokens_to_ids(
        model.audio_token
    )

    audio_pos = input_ids[0].tolist().index(audio_token)

    print("Audio token position:", audio_pos)

    # --------------------------------------------------------
    # 3. Audio is already 16 kHz
    # --------------------------------------------------------

    processed_audio = audio

    print("Audio sample rate:", orig_sr)
    print("Audio samples:", len(processed_audio))

    # --------------------------------------------------------
    # 4. Feature extraction
    # --------------------------------------------------------

    audio_features = model.processor.feature_extractor(
        [processed_audio],
        sampling_rate=model.sampling_rate,
        return_tensors="pt"
    ).input_features

    # Convert float32 → encoder dtype (BF16)
    encoder_dtype = model.encoder.conv1.weight.dtype

    audio_features = audio_features.to(
        device=device,
        dtype=encoder_dtype
    )

    print("Audio feature dtype:", audio_features.dtype)
    print("Encoder dtype:", encoder_dtype)

    # --------------------------------------------------------
    # 5. Whisper encoder
    # --------------------------------------------------------

    with torch.no_grad():
        audio_embeddings = model.encoder(
            audio_features
        ).last_hidden_state

    print("Encoder output:", audio_embeddings.shape)
    print("Encoder output dtype:", audio_embeddings.dtype)

    # --------------------------------------------------------
    # 6. Projector
    # --------------------------------------------------------

    projector_dtype = next(
        model.projector.parameters()
    ).dtype

    print("Projector dtype:", projector_dtype)

    audio_embeddings_for_projector = audio_embeddings.to(
        projector_dtype
    )

    with torch.no_grad():
        projected_audio_embeddings = model.projector(
            audio_embeddings_for_projector
        )

    print(
        "Projected audio:",
        projected_audio_embeddings.shape
    )

    print(
        "Projected audio dtype:",
        projected_audio_embeddings.dtype
    )

    # --------------------------------------------------------
    # 7. Decoder text embeddings
    # --------------------------------------------------------

    input_embeddings = model.decoder.get_input_embeddings()(
        input_ids
    )

    decoder_dtype = input_embeddings.dtype

    print("Decoder dtype:", decoder_dtype)

    # Projector FP32 → decoder BF16
    projected_audio_embeddings = (
        projected_audio_embeddings.to(decoder_dtype)
    )

    # --------------------------------------------------------
    # 8. Shapes
    # --------------------------------------------------------

    batch_size, input_seq_len, embed_dim = (
        input_embeddings.shape
    )

    audio_seq_len = projected_audio_embeddings.shape[1]

    combined_len = (
        input_seq_len +
        audio_seq_len -
        1
    )

    # --------------------------------------------------------
    # 9. Combined embeddings
    # --------------------------------------------------------

    combined_embeddings = torch.zeros(
        batch_size,
        combined_len,
        embed_dim,
        device=device,
        dtype=decoder_dtype
    )

    combined_attention_mask = torch.zeros(
        batch_size,
        combined_len,
        device=device,
        dtype=torch.long
    )

    # --------------------------------------------------------
    # 10. Text before audio
    # --------------------------------------------------------

    combined_embeddings[
        :, :audio_pos
    ] = input_embeddings[
        :, :audio_pos
    ]

    combined_attention_mask[
        :, :audio_pos
    ] = 1

    # --------------------------------------------------------
    # 11. Audio embeddings
    # --------------------------------------------------------

    combined_embeddings[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = projected_audio_embeddings

    combined_attention_mask[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = 1

    # --------------------------------------------------------
    # 12. Text after audio
    # --------------------------------------------------------

    suffix_start = audio_pos + 1
    suffix_len = input_seq_len - suffix_start

    out_start = audio_pos + audio_seq_len

    if suffix_len > 0:

        combined_embeddings[
            :,
            out_start:out_start + suffix_len
        ] = input_embeddings[
            :,
            suffix_start:
        ]

        combined_attention_mask[
            :,
            out_start:out_start + suffix_len
        ] = 1

    # --------------------------------------------------------
    # 13. Final checks
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("FINAL CHECK")
    print("=" * 70)

    print(
        "Combined embeddings:",
        combined_embeddings.shape
    )

    print(
        "Combined dtype:",
        combined_embeddings.dtype
    )

    print(
        "Attention mask:",
        combined_attention_mask.shape
    )

    # --------------------------------------------------------
    # 14. Test decoder forward
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("DECODER FORWARD TEST")
    print("=" * 70)

    with torch.no_grad():

        test_output = model.decoder(
            inputs_embeds=combined_embeddings,
            attention_mask=combined_attention_mask,
            use_cache=False
        )

    print("Decoder forward: SUCCESS")
    print("Logits shape:", test_output.logits.shape)

    # IMPORTANT:
    # Return the embeddings so we can use them
    # in the next generation step.

    return (
        combined_embeddings,
        combined_attention_mask
    )

combined_embeddings, combined_attention_mask = (
    parrotlet_transcribe_fixed(
        model=model,
        audio=audio_16k,
        orig_sr=16000,
        max_new_tokens=128
    )
)

print("Embeddings:", combined_embeddings.shape)
print("Embedding dtype:", combined_embeddings.dtype)
print("Attention mask:", combined_attention_mask.shape)

decoder = model.decoder

print("=" * 70)
print("PARROTLET DECODER DIAGNOSTIC")
print("=" * 70)

print("Decoder class:")
print(type(decoder))

print()
print("BOS token ID :", model.tokenizer.bos_token_id)
print("EOS token ID :", model.tokenizer.eos_token_id)
print("PAD token ID :", model.tokenizer.pad_token_id)

print()
print("Generation config:")
print(decoder.generation_config)

print()
print("Decoder config:")
print(decoder.config.model_type)

print()
print("Combined embeddings:")
print(combined_embeddings.shape)

print("Combined attention mask:")
print(combined_attention_mask.shape)

import torch
import time

def generate_transcript(
    model,
    combined_embeddings,
    combined_attention_mask,
    max_new_tokens=128,
    repetition_penalty=1.2
):
    decoder = model.decoder
    tokenizer = model.tokenizer

    device = combined_embeddings.device

    print("=" * 70)
    print("PARROTLET TOKEN GENERATION")
    print("=" * 70)

    generated_tokens = []

    # --------------------------------------------------------
    # FIRST FORWARD PASS
    # Process the complete audio + prompt sequence
    # --------------------------------------------------------

    print("Processing audio + prompt...")

    with torch.no_grad():
        outputs = decoder(
            inputs_embeds=combined_embeddings,
            attention_mask=combined_attention_mask,
            use_cache=True
        )

    past_key_values = outputs.past_key_values

    # Last position predicts the first transcription token
    logits = outputs.logits[:, -1, :].clone()

    # --------------------------------------------------------
    # GENERATION LOOP
    # --------------------------------------------------------

    for step in range(max_new_tokens):

        # --------------------------------------------
        # Repetition penalty
        # --------------------------------------------

        if repetition_penalty != 1.0 and generated_tokens:

            for token_id in set(generated_tokens):

                if logits[0, token_id] < 0:
                    logits[0, token_id] *= repetition_penalty
                else:
                    logits[0, token_id] /= repetition_penalty

        # --------------------------------------------
        # Greedy decoding
        # --------------------------------------------

        next_token = torch.argmax(
            logits,
            dim=-1
        )

        token_id = next_token.item()

        generated_tokens.append(token_id)

        # --------------------------------------------
        # Check EOS
        # --------------------------------------------

        if token_id in [1, 106]:
            print("EOS reached at token:", step + 1)
            break

        # --------------------------------------------
        # Show progress
        # --------------------------------------------

        if (step + 1) % 10 == 0:
            current_text = tokenizer.decode(
                generated_tokens,
                skip_special_tokens=True
            )

            print(
                f"Tokens: {step + 1} | "
                f"Text: {current_text}"
            )

        # --------------------------------------------
        # Embed newly generated token
        # --------------------------------------------

        next_embedding = decoder.get_input_embeddings()(
            next_token.unsqueeze(0)
        )

        # --------------------------------------------
        # Extend attention mask
        # --------------------------------------------

        new_attention_mask = torch.cat(
            [
                combined_attention_mask,
                torch.ones(
                    (1, 1),
                    dtype=combined_attention_mask.dtype,
                    device=device
                )
            ],
            dim=1
        )

        # --------------------------------------------
        # Forward only the new token
        # --------------------------------------------

        with torch.no_grad():

            outputs = decoder(
                inputs_embeds=next_embedding,
                attention_mask=new_attention_mask,
                past_key_values=past_key_values,
                use_cache=True
            )

        past_key_values = outputs.past_key_values

        logits = outputs.logits[:, -1, :].clone()

        combined_attention_mask = new_attention_mask

    # --------------------------------------------------------
    # DECODE
    # --------------------------------------------------------

    transcript = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    return transcript, generated_tokens


# ============================================================
# RUN
# ============================================================

start_time = time.time()

transcript, generated_tokens = generate_transcript(
    model=model,
    combined_embeddings=combined_embeddings,
    combined_attention_mask=combined_attention_mask,
    max_new_tokens=128,
    repetition_penalty=1.2
)

elapsed = time.time() - start_time


# ============================================================
# RESULT
# ============================================================

print()
print("=" * 70)
print("PARROTLET-A 2.5 PRO — ENGLISH TRANSCRIPTION")
print("=" * 70)

print(transcript)

print()
print("Generated tokens:", len(generated_tokens))
print("Generation time:", round(elapsed, 2), "seconds")
print("=" * 70)

import torch

def build_parrotlet_embeddings(
    model,
    audio,
    prompt
):
    device = next(model.parameters()).device

    # --------------------------------------------------------
    # Tokenize prompt
    # --------------------------------------------------------

    input_ids = torch.tensor(
        model.tokenizer(
            prompt,
            add_special_tokens=False
        )["input_ids"],
        dtype=torch.long,
        device=device
    ).unsqueeze(0)

    input_attention_mask = torch.ones_like(input_ids)

    # --------------------------------------------------------
    # Find audio token
    # --------------------------------------------------------

    audio_token = model.tokenizer.convert_tokens_to_ids(
        model.audio_token
    )

    audio_pos = input_ids[0].tolist().index(audio_token)

    # --------------------------------------------------------
    # Audio features
    # --------------------------------------------------------

    audio_features = model.processor.feature_extractor(
        [audio],
        sampling_rate=model.sampling_rate,
        return_tensors="pt"
    ).input_features

    encoder_dtype = model.encoder.conv1.weight.dtype

    audio_features = audio_features.to(
        device=device,
        dtype=encoder_dtype
    )

    # --------------------------------------------------------
    # Whisper encoder
    # --------------------------------------------------------

    with torch.no_grad():
        audio_embeddings = model.encoder(
            audio_features
        ).last_hidden_state

    # --------------------------------------------------------
    # Projector
    # --------------------------------------------------------

    projector_dtype = next(
        model.projector.parameters()
    ).dtype

    with torch.no_grad():
        projected_audio_embeddings = model.projector(
            audio_embeddings.to(projector_dtype)
        )

    # --------------------------------------------------------
    # Decoder embeddings
    # --------------------------------------------------------

    input_embeddings = model.decoder.get_input_embeddings()(
        input_ids
    )

    decoder_dtype = input_embeddings.dtype

    projected_audio_embeddings = (
        projected_audio_embeddings.to(decoder_dtype)
    )

    # --------------------------------------------------------
    # Combine text + audio
    # --------------------------------------------------------

    batch_size, input_seq_len, embed_dim = (
        input_embeddings.shape
    )

    audio_seq_len = projected_audio_embeddings.shape[1]

    combined_len = (
        input_seq_len +
        audio_seq_len -
        1
    )

    combined_embeddings = torch.zeros(
        batch_size,
        combined_len,
        embed_dim,
        device=device,
        dtype=decoder_dtype
    )

    combined_attention_mask = torch.zeros(
        batch_size,
        combined_len,
        device=device,
        dtype=torch.long
    )

    # Text before audio
    combined_embeddings[
        :, :audio_pos
    ] = input_embeddings[
        :, :audio_pos
    ]

    combined_attention_mask[
        :, :audio_pos
    ] = 1

    # Audio
    combined_embeddings[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = projected_audio_embeddings

    combined_attention_mask[
        :,
        audio_pos:audio_pos + audio_seq_len
    ] = 1

    # Text after audio
    suffix_start = audio_pos + 1
    suffix_len = input_seq_len - suffix_start
    out_start = audio_pos + audio_seq_len

    if suffix_len > 0:
        combined_embeddings[
            :,
            out_start:out_start + suffix_len
        ] = input_embeddings[
            :,
            suffix_start:
        ]

        combined_attention_mask[
            :,
            out_start:out_start + suffix_len
        ] = 1

    return combined_embeddings, combined_attention_mask

english_prompt = """<bos><start_of_turn>user
You are an English speech transcriptionist.

Transcribe the audio verbatim.

The audio is in English.
Output the transcription in English using Latin/English characters only.
Do not translate the speech.
Do not transliterate English speech into Telugu, Tamil, Hindi, or any other Indian script.

<|audio_bos|><audio><|audio_eos|>
Transcribe this audio.<end_of_turn>
<start_of_turn>model
"""

print(english_prompt)

english_embeddings, english_attention_mask = (
    build_parrotlet_embeddings(
        model=model,
        audio=audio_16k,
        prompt=english_prompt
    )
)

print("Embeddings:", english_embeddings.shape)
print("Dtype:", english_embeddings.dtype)
print("Attention mask:", english_attention_mask.shape)

start_time = time.time()

english_transcript, english_tokens = generate_transcript(
    model=model,
    combined_embeddings=english_embeddings,
    combined_attention_mask=english_attention_mask,
    max_new_tokens=128,
    repetition_penalty=1.2
)

elapsed = time.time() - start_time

print()
print("=" * 70)
print("ENGLISH-PROMPT PARROTLET RESULT")
print("=" * 70)

print(english_transcript)

print()
print("Generated tokens:", len(english_tokens))
print("Generation time:", round(elapsed, 2), "seconds")

def fixed_preprocess_audio(audio_data, orig_sr):
    if orig_sr != model.sampling_rate:
        import librosa
        audio_data = librosa.resample(
            audio_data,
            orig_sr=orig_sr,
            target_sr=model.sampling_rate,
            res_type="soxr_vhq"
        )
    return audio_data

model.preprocess_audio = fixed_preprocess_audio

import torch
import time


def generate_parrotlet_transcript(
    model,
    combined_embeddings,
    combined_attention_mask,
    max_new_tokens=128,
    repetition_penalty=1.2,
):
    decoder = model.decoder
    tokenizer = model.tokenizer

    device = combined_embeddings.device

    print("=" * 70)
    print("PARROTLET-A 2.5 PRO — TOKEN GENERATION")
    print("=" * 70)

    # --------------------------------------------------------
    # First pass: process complete audio + prompt
    # --------------------------------------------------------

    print("Processing audio + prompt...")

    with torch.no_grad():
        outputs = decoder(
            inputs_embeds=combined_embeddings,
            attention_mask=combined_attention_mask,
            use_cache=True,
        )

    past_key_values = outputs.past_key_values

    # Last position predicts first transcript token
    logits = outputs.logits[:, -1, :].clone()

    generated_tokens = []

    # --------------------------------------------------------
    # Autoregressive generation
    # --------------------------------------------------------

    for step in range(max_new_tokens):

        # Repetition penalty
        if repetition_penalty != 1.0 and generated_tokens:

            for token_id in set(generated_tokens):

                if logits[0, token_id] < 0:
                    logits[0, token_id] *= repetition_penalty
                else:
                    logits[0, token_id] /= repetition_penalty

        # Greedy decoding
        next_token = torch.argmax(
            logits,
            dim=-1,
            keepdim=True,
        )

        token_id = next_token.item()

        generated_tokens.append(token_id)

        # EOS tokens from Parrotlet configuration
        if token_id in [1, 106]:
            print(
                "EOS reached at token:",
                step + 1
            )
            break

        # Show progress
        if (step + 1) % 10 == 0:

            partial_text = tokenizer.decode(
                generated_tokens,
                skip_special_tokens=True,
            )

            print(
                f"Tokens: {step + 1} | "
                f"Text: {partial_text}"
            )

        # ----------------------------------------------------
        # Convert new token to embedding
        # ----------------------------------------------------

        next_embedding = decoder.get_input_embeddings()(
            next_token
        )

        # ----------------------------------------------------
        # Extend attention mask
        # ----------------------------------------------------

        new_attention_mask = torch.cat(
            [
                combined_attention_mask,
                torch.ones(
                    (1, 1),
                    dtype=combined_attention_mask.dtype,
                    device=device,
                ),
            ],
            dim=1,
        )

        # ----------------------------------------------------
        # Process only newly generated token
        # ----------------------------------------------------

        with torch.no_grad():

            outputs = decoder(
                inputs_embeds=next_embedding,
                attention_mask=new_attention_mask,
                past_key_values=past_key_values,
                use_cache=True,
            )

        past_key_values = outputs.past_key_values

        logits = outputs.logits[:, -1, :].clone()

        combined_attention_mask = new_attention_mask

    # --------------------------------------------------------
    # Decode final tokens
    # --------------------------------------------------------

    transcript = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True,
    ).strip()

    return transcript, generated_tokens


# ============================================================
# RUN TRANSCRIPTION
# ============================================================

start_time = time.time()

transcript, generated_tokens = generate_parrotlet_transcript(
    model=model,
    combined_embeddings=combined_embeddings,
    combined_attention_mask=combined_attention_mask,
    max_new_tokens=128,
    repetition_penalty=1.2,
)

elapsed = time.time() - start_time


# ============================================================
# RESULT
# ============================================================

print()
print("=" * 70)
print("PARROTLET-A 2.5 PRO — TRANSCRIPTION")
print("=" * 70)

print(transcript)

print()
print("Generated tokens:", len(generated_tokens))
print("Generation time:", round(elapsed, 2), "seconds")

print("=" * 70)